############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2
#hasChilden = true

[[main]]
name = "Designs"
url = "designs/"
weight = 3

# [[main]]
# name = "Contact"
# url =  "contact/"
# weight = 4

# [[main]]
# #parent = "About"
# name = "CV"
# url = "cv_julija_martinkute.pdf"
# weight = 5

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
